### ISSUE TITLE
Add the ability to generate anonymised exports

### ISSUE THREAD

**Issue by punkstar** [meanbee/magedbm2#2]
### Background

The current process for creating our database dumps strips out sensitive tables which is great for development environments, due to it reducing the size of the dump itself. For diagnosing and fixing some client issues, however, the volume of data is key. Any reasonable security policy will prevent developers from importing sensitive customer data into development environments, so we need to support obfuscation of certain columns in specific tables.

### Related Projects

* [divanteltd/anonymizer](https://github.com/divanteltd/anonymizer) (ruby)
* [mavenlink/my_obfuscate](https://github.com/mavenlink/my_obfuscate) (ruby)

### Requirements

* As a developer I should be able to specify which columns in tables that I want anonymised
* As a developer I should be able to keep anonymisation configuration in my project's version control system
* As a developer I should be able to specify whether or not I want to generate a stripped database backup or an anonymised backup

### Approach
The plan to start off with is to use one of the tools in the _Related Projects_ section to do the anonymisation for us. Stream reading and modifying an SQL dump is a project in itself, so it would be wise for us to stay focused on the overall role of this project and tool. This does introduce a dependency on having ruby available on the machine (unless we can find a PHP equivalent), but that’s ok for the time being. Medium to long term, narrowing down the requirements to just PHP is the aim.

### Tasks

- [x] Generate an anonymised export
- [x] Import an anonymised export
- [x] Upload exports to S3
- [x] Download exports from S3
- [x] Allow anonymization rules to be driven by configuration
- [x] Allow for the specification of a project specific configuration file

**Comment by tgerulaitis** [comment]
Just a note/correction on the impact of using one of the ruby libraries for anonymising data. Currently, `magedbm2` is available as a portable `phar`, but having parts of it depending on ruby _and_ specific ruby packages that are not build into ruby itself means that installing `magedbm2` is going to get a lot more complicated.

**Comment by punkstar** [comment]
A couple of things that need to be discussed before we start this:

**Configuration Files**

With the move away from Magerun (in #5) I added a load of configuration that needed to be shipped with this tool, specifically the "table groups" (e.g. the expansion of `@development`) that are used when deciding which tables to strip from an export.

To achieve this I added a base configuration file that's embedded in the phar and is the first file that's loaded when building the configuration object. Any user specific `~/.magedbm/config.yml` file or command line options then overwrite the loaded config options. This layering of configuration files seems like a pretty clean approach to building up the final configuration object.

I propose the following:

- We use this config file approach for defining which tables should be anonymised in an export
- We introduce another file that is stored in a project's repo which contains (non-sensitive) magedbm2 specific configuration, such as these anonymisation parameters.

**Supporting EAV**

Due to the fact that Magento uses EAV to store a bunch of its data this isn't going to be as simple as defining the columns in a table that we want to anonymise. We need the ability to selectively anonymise rows based on its contents.

As I see it, there's two routes that we can take here:

*Explicitly defining conditions on rows*

We use the project specific configuration file and manually define the rows to anonymise and conditions on those rows by hardcoding values. I'm thinking something like:

```
customer_entity:
  firstname:
    # Type means that we should use https://github.com/fzaninotto/Faker
    # to generate a new name.
    type: name

customer_entity_datetime:
  value:
    type: datetime
    # Manually specify that, in our database, date of birth is stored as
    # attribute with ID 11. This could be different for other projects.
    filter:
      attribute_id: [11]
```

This approach would be the simplest in its implementation. We'd be able to stream the file into a program, analyse a row at a time and apply the filters. This could be brittle though and risks us generating "anonymised" dumps which could anonymise the wrong rows should the attribute IDs change in the future.

*Configuration file that supports EAV*

We create a configuration file that is Magento specific and natively supports EAV tables.

```
tables:
  customer_entity:
    firstname:
      type: name
eav:
  customer:
    dob:
      type: datetime
```

This approach would be good from a user's perspective as there's no need to check that the correct attributes are still be sanitised. To implement this we'd first need to read in the `eav_attributes` table when dumping to build up our attribute code-to-id map and then use that when anonymising.

With this approach we could ship a default anonymisation profile (like we ship a default `@development` strip table group) that could be used to anonymise a Magento 2 project out of the box.

**Using an external tool**

https://github.com/mavenlink/my_obfuscate

✅ Supports lambdas for dynamically deciding what to do with a row (that would allow us to implement the non-EAV configuration file approach)
✅ Currently looks like the best bit for our execution model as it can be stuck in a pipe between the `mysqldump` and the `gzip`
⚠️ It doesn't appear to be actively maintained (there's an issue open saying that the published gem doesn't have a feature in it, and that `master` should be used)
⚠️ Written in Ruby

https://github.com/DivanteLtd/anonymizer

✅ Supports Magento already and has the EAV problem solved
⚠️ Doesn't support our execution model, so we'll need to edit our database service to use this
⚠️ Written in Ruby

https://github.com/digilist/SnakeDumper

✅ Supports "filters" that would allow us to implement the non-EAV configuration file approach
⚠️ Doesn't support our execution model, so we'll need to edit our database service to use this
⚠️ It doesn't appear to be actively maintained
✅ Written in PHP

**Comment by tgerulaitis** [comment]
https://github.com/SwiftOtter/Driver might be worth a look. I think it was built to work with Magento.

**Comment by punkstar** [comment]
After discussing with @tgerulaitis, the route that I've decided to go here is to generate an additional file that contains the anonymised data to be applied after the initial stripped database has been imported.

I'm currently experimenting with using `--xml` on `mysqldump`, anonymising the data in the XML file, then importing that XML file with `mysql`.
